#pragma once
#include <stdint.h>

class ExpertAction
{
public:
	static void UpdateAddresses();

	static void AcknowledgeEvent(int eventType, int id);
	static void AcknowledgeTaunt(int playerNumber, int tauntId);
	static void AttackNow();
	static void Build(int buildingType);
	static void BuildForward(int buildingType);
	static void BuildGate(int perimeter);
	static void BuildWall(int perimeter, int wallType);
	static void BuyCommodity(int commodityType);
	static void CcAddResource(int resourceType, int amount);
	static void ChatDebug(int text);
	static void ChatLocal(int text);
	static void ChatLocalUsingId(int stringId);
	static void ChatLocalUsingRange(int stringIdStart, int stringIdRange);
	static void ChatLocalToSelf(int text);
	static void ChatToAll(int text);
	static void ChatToAllUsingId(int stringId);
	static void ChatToAllUsingRange(int stringIdStart, int stringIdRange);
	static void ChatToAllies(int text);
	static void ChatToAlliesUsingId(int stringId);
	static void ChatToAlliesUsingRange(int stringIdStart, int stringIdRange);
	static void ChatToEnemies(int text);
	static void ChatToEnemiesUsingId(int stringId);
	static void ChatToEnemiesUsingRange(int stringIdStart, int stringIdRange);
	static void ChatToPlayer(int playerNumber, int text);
	static void ChatToPlayerUsingId(int playerNumber, int stringId);
	static void ChatToPlayerUsingRange(int playerNumber, int stringIdStart, int stringIdRange);
	static void ChatTrace(int traceNumber);
	static void ClearTributeMemory(int playerNumber, int resourceType);
	static void DeleteBuilding(int buildingType);
	static void DeleteUnit(int unitType);
	static void DisableRule(int groupId);
	static void DisableSelf();
	static void DisableTimer(int timerId);
	static void DoNothing();
	static void EnableRule(int groupId);
	static void EnableTimer(int timerId, int timeInterval);
	static void EnableWallPlacement(int perimeter);
	static void FeBreakPoint(int param1, int param2, int param3, int param4);
	static void GenerateRandomNumber(int range);
	static void Log(int text);
	static void LogTrace(int traceNumber);
	static void ReleaseEscrow(int resourceType);
	static void Research(int researchType);
	static void Resign();
	static void SellCommodity(int commodityType);
	static void SetAuthorName(int name);
	static void SetAuthorEmail(int email);
	static void SetAuthorVersion(int version);
	static void SetDifficultyParameter(int difficultyParameter, int value);
	static void SetDoctrine(int doctrine);
	static void SetEscrowPercentage(int resourceType, int percentage);
	static void SetGoal(int goalId, int goalValue);
	static void SetSharedGoal(int goalId, int goal);
	static void SetSignal(int signalId);
	static void SetStance(int playerNumber, int stance);
	static void SetStrategicNumber(int strategicNumber, int value);
	static void SkyboxClearSignal(int param);
	static void SkyboxSetNameMode(int param);
	static void Spy();
	static void Taunt(int tauntNumber);
	static void TauntUsingRange(int tauntIdStart, int tauntIdRange);
	static void Train(int unitType);
	static void TributeToPlayer(int playerNumber, int resourceType, int tributeAmount);
	static void UpAddCostData(int goalId, int typeOp, int opValue);
	static void UpAddObjectById(int searchSource, int typeOp, int opId);
	static void UpAddObjectCost(int typeOp1, int objectId, int typeOp2, int value);
	static void UpAddPoint(int goalPoint1, int goalPoint2, int typeOp, int count);
	static void UpAddResearchCost(int typeOp1, int techId, int typeOp2, int value);
	static void UpAssignBuilders(int typeOp1, int buildingId, int typeOp2, int value);
	static void UpBoundPoint(int goalPoint1, int goalPoint2);
	static void UpBoundPrecisePoint(int goalPoint, int precise, int typeOp, int border);
	static void UpBuild(int placementType, int escrowState, int typeOp, int buildingId);
	static void UpBuildLine(int goalPoint1, int goalPoint2, int typeOp, int buildingId);
	static void UpBuyCommodity(int typeOp1, int resourceAmount, int typeOp2, int value);
	static void UpCcAddResource(int typeOp1, int resourceAmount, int typeOp2, int value);
	static void UpCcSendCheat(int code);
	static void UpChangeName(int newName);
	static void UpChatDataToAll(int format, int typeOp, int value);
	static void UpChatDataToAllUsingId(int param1, int stringId, int param3);
	static void UpChatDataToPlayerUsingId(int stringId, int playerId, int param3, int param4);
	static void UpChatDataToPlayer(int player, int format, int typeOp, int value);
	static void UpChatDataToSelf(int format, int typeOp, int value);
	static void UpCleanSearch(int searchSource, int objectData, int searchOrder);
	static void UpCopyPoint(int goalPoint1, int goalPoint2);
	static void UpCreateGroup(int goalIndex, int goalCount, int typeOp, int groupId);
	static void UpCrossTiles(int goalPoint1, int goalPoint2, int typeOp, int tiles);
	static void UpDeleteDistantFarms(int typeOp, int value);
	static void UpDeleteIdleUnits(int idleType);
	static void UpDeleteObjects(int typeOp1, int unitId, int typeOp2, int hitpoints);
	static void UpDisbandGroupType(int groupType);
	static void UpDropResources(int resource, int typeOp, int value);
	static void UpFilterDistance(int typeOp1, int minDistance, int typeOp2, int maxDistance);
	static void UpFilterExclude(int cmdId, int actionId, int orderId, int classId);
	static void UpFilterGarrison(int typeOp1, int minGarrison, int typeOp2, int maxGarrison);
	static void UpFilterInclude(int cmdId, int actionId, int orderId, int onMainland);
	static void UpFilterRange(int minGarrison, int maxGarrison, int minDistance, int maxDistance);
	static void UpFilterStatus(int typeOp1, int objectStatus, int typeOp2, int objectList);
	static void UpFindFlare(int goalPoint);
	static void UpFindLocal(int typeOp1, int unitId, int typeOp2, int count);
	static void UpFindNextPlayer(int playerStance, int findPlayerMethod, int goalPlayerId);
	static void UpFindPlayer(int playerStance, int findPlayerMethod, int goalPlayerId);
	static void UpFindPlayerFlare(int player, int goalPoint);
	static void UpFindRemote(int typeOp1, int unitId, int typeOp2, int count);
	static void UpFindResource(int typeOp1, int resource, int typeOp2, int count);
	static void UpFindStatusLocal(int typeOp1, int unitId, int typeOp2, int count);
	static void UpFindStatusRemote(int typeOp1, int unitId, int typeOp2, int count);
	static void UpFullResetSearch();
	static void UpGarrison(int objectId, int typeOp, int unitId);
	static void UpGatherInside(int typeOp1, int buildingId, int typeOp2, int state);
	static void UpGetAttackerClass(int goalSourceClass);
	static void UpGetCostDelta(int goalId);
	static void UpGetEvent(int typeOp, int eventId, int goalValue);
	static void UpGetFact(int factId, int factParam, int goalId);
	static void UpGetFactMax(int player, int factId, int param, int goalData);
	static void UpGetFactMin(int player, int factId, int param, int goalData);
	static void UpGetFactSum(int player, int factId, int param, int goalData);
	static void UpGetFocusFact(int factId, int param, int goalData);
	static void UpGetGroupSize(int typeOp, int groupId, int goalSize);
	static void UpGetGuardState(int goalState);
	static void UpGetIndirectGoal(int typeOp1, int goalId, int goalValue);
	static void UpGetObjectData(int objectData, int goalData);
	static void UpGetObjectTargetData(int objectData, int goalData);
	static void UpGetObjectTypeData(int typeOp, int objectTypeId, int objectData, int goalData);
	static void UpGetPathDistance(int goalPoint, int strict, int goalData);
	static void UpGetPlayerColor(int player, int goalColorId);
	static void UpGetPlayerFact(int player, int factId, int param, int goalData);
	static void UpGetPoint(int positionType, int goalPoint);
	static void UpGetPointContains(int goalPoint, int goalId, int typeOp, int objectId);
	static void UpGetPointDistance(int goalPoint1, int goalPoint2, int goalDistance);
	static void UpGetPointElevation(int goalPoint, int goalData);
	static void UpGetPointTerrain(int goalPoint, int goalTerrain);
	static void UpGetPointZone(int goalPoint, int goalData);
	static void UpGetPreciseTime(int goalStart, int goalTime);
	static void UpGetProjectilePlayer(int projectileType, int goalPlayerId);
	static void UpGetRuleId(int goalRuleId);
	static void UpGetSearchState(int goalState);
	static void UpGetSharedGoal(int typeOp, int sharedGoalId, int goalValue);
	static void UpGetSignal(int typeOp, int signalId, int goalValue);
	static void UpGetTargetFact(int factId, int param, int goalData);
	static void UpGetThreatData(int goalElapsedTime, int goalPlayerId, int goalSourceClass, int goalTargetClass);
	static void UpGetTimer(int typeOp, int timerId, int goalValue);
	static void UpGetTreatyData(int param);
	static void UpGetUpgradeId(int player, int count, int goalTypeId, int goalUpgradeId);
	static void UpGetVictoryData(int goalPlayerId, int goalType, int goalTime);
	static void UpGetVictoryLimit(int goalLimit);
	static void UpGuardUnit(int objectId, int typeOp, int unitId);
	static void UpJumpDirect(int typeOp, int ruleId);
	static void UpJumpDynamic(int typeOp, int ruleDelta);
	static void UpJumpRule(int ruleDelta);
	static void UpLerpPercent(int goalPoint1, int goalPoint2, int typeOp, int percent);
	static void UpLerpTiles(int goalPoint1, int goalPoint2, int typeOp, int tiles);
	static void UpLogData(int plain, int format, int typeOp, int value);
	static void UpModifyEscrow(int resource, int mathOp, int value);
	static void UpModifyFlag(int goalId, int mathOp, int value);
	static void UpModifyGoal(int goalId, int mathOp, int value);
	static void UpModifyGroupFlag(int on, int typeOp, int groupId);
	static void UpModifySn(int snId, int mathOp, int value);
	static void UpReleaseEscrow();
	static void UpRemoveObjects(int searchSource, int objectData, int typeOp, int value);
	static void UpRequestHunters(int typeOp, int value);
	static void UpResearch(int escrowState, int typeOp, int techId);
	static void UpResetAttackNow();
	static void UpResetBuilding(int preserveResearch, int typeOp, int buildingId);
	static void UpResetCostData(int goalId);
	static void UpResetFilters();
	static void UpResetGroup(int typeOp, int groupId);
	static void UpResetPlacement(int typeOp, int buildingId);
	static void UpResetScouts();
	static void UpResetSearch(int localIndex, int localList, int remoteIndex, int remoteList);
	static void UpResetTargetPriorities(int priorityType, int mode);
	static void UpResetUnit(int typeOp, int unitId);
	static void UpRetaskGatherers(int resource, int typeOp, int value);
	static void UpRetreatNow();
	static void UpRetreatTo(int objectId, int typeOp, int unitId);
	static void UpSellCommodity(int typeOp1, int resourceAmount, int typeOp2, int value);
	static void UpSendFlare(int goalPoint);
	static void UpSendScout(int groupType, int positionType);
	static void UpSetAttackStance(int unitId, int typeOp, int attackStance);
	static void UpSetDefensePriority(int typeOp1, int buildingId, int typeOp2, int value);
	static void UpSetEvent(int typeOp1, int eventId, int typeOp2, int value);
	static void UpSetGroup(int searchSource, int typeOp, int groupId);
	static void UpSetIndirectGoal(int typeOp1, int goalId, int typeOp2, int value);
	static void UpSetOffensePriority(int typeOp1, int objectId, int typeOp2, int value);
	static void UpSetPlacementData(int playerAlly, int objectId, int typeOp, int value);
	static void UpSetPreciseTargetPoint(int goalPoint);
	static void UpSetSharedGoal(int typeOp1, int sharedGoalId, int typeOp2, int value);
	static void UpSetSignal(int typeOp1, int signalId, int typeOp2, int value);
	static void UpSetTargetById(int typeOp, int id);
	static void UpSetTargetObject(int searchSource, int typeOp, int index);
	static void UpSetTargetPoint(int goalPoint);
	static void UpSetTimer(int typeOp1, int timerId, int typeOp2, int value);
	static void UpSetupCostData(int resetCost, int goalId);
	static void UpStoreMapName(int extension);
	static void UpStoreObjectName();
	static void UpStorePlayerChat(int player);
	static void UpStorePlayerName(int player);
	static void UpStoreTechName(int typeOp, int techId);
	static void UpStoreText(int typeOp, int languageId);
	static void UpStoreTypeName(int typeOp, int objectTypeId);
	static void UpTargetObjects(int target, int action, int formation, int attackStance);
	static void UpTargetPoint(int goalPoint, int action, int formation, int attackStance);
	static void UpTestharnessReport(int param1, int param2, int param3);
	static void UpTestharnessTest(int param1, int param2, int param3, int param4);
	static void UpTrain(int escrowState, int typeOp, int unitId);
	static void UpTributeToPlayer(int player, int resourceAmount, int typeOp, int value);
	static void UpUngarrison(int typeOp, int objectId);
	static void UpUpdateTargets();

private:
	ExpertAction() {};

	inline static void(__fastcall* FuncAcknowledgeEvent)(int eventType, int id) = 0;
	inline static void(__fastcall* FuncAcknowledgeTaunt)(int playerNumber, int tauntId) = 0;
	inline static void(__fastcall* FuncAttackNow)() = 0;
	inline static void(__fastcall* FuncBuild)(int buildingType) = 0;
	inline static void(__fastcall* FuncBuildForward)(int buildingType) = 0;
	inline static void(__fastcall* FuncBuildGate)(int perimeter) = 0;
	inline static void(__fastcall* FuncBuildWall)(int perimeter, int wallType) = 0;
	inline static void(__fastcall* FuncBuyCommodity)(int commodityType) = 0;
	inline static void(__fastcall* FuncCcAddResource)(int resourceType, int amount) = 0;
	inline static void(__fastcall* FuncChatDebug)(int text) = 0;
	inline static void(__fastcall* FuncChatLocal)(int text) = 0;
	inline static void(__fastcall* FuncChatLocalUsingId)(int stringId) = 0;
	inline static void(__fastcall* FuncChatLocalUsingRange)(int stringIdStart, int stringIdRange) = 0;
	inline static void(__fastcall* FuncChatLocalToSelf)(int text) = 0;
	inline static void(__fastcall* FuncChatToAll)(int text) = 0;
	inline static void(__fastcall* FuncChatToAllUsingId)(int stringId) = 0;
	inline static void(__fastcall* FuncChatToAllUsingRange)(int stringIdStart, int stringIdRange) = 0;
	inline static void(__fastcall* FuncChatToAllies)(int text) = 0;
	inline static void(__fastcall* FuncChatToAlliesUsingId)(int stringId) = 0;
	inline static void(__fastcall* FuncChatToAlliesUsingRange)(int stringIdStart, int stringIdRange) = 0;
	inline static void(__fastcall* FuncChatToEnemies)(int text) = 0;
	inline static void(__fastcall* FuncChatToEnemiesUsingId)(int stringId) = 0;
	inline static void(__fastcall* FuncChatToEnemiesUsingRange)(int stringIdStart, int stringIdRange) = 0;
	inline static void(__fastcall* FuncChatToPlayer)(int playerNumber, int text) = 0;
	inline static void(__fastcall* FuncChatToPlayerUsingId)(int playerNumber, int stringId) = 0;
	inline static void(__fastcall* FuncChatToPlayerUsingRange)(int playerNumber, int stringIdStart, int stringIdRange) = 0;
	inline static void(__fastcall* FuncChatTrace)(int traceNumber) = 0;
	inline static void(__fastcall* FuncClearTributeMemory)(int playerNumber, int resourceType) = 0;
	inline static void(__fastcall* FuncDeleteBuilding)(int buildingType) = 0;
	inline static void(__fastcall* FuncDeleteUnit)(int unitType) = 0;
	inline static void(__fastcall* FuncDisableRule)(int groupId) = 0;
	inline static void(__fastcall* FuncDisableSelf)() = 0;
	inline static void(__fastcall* FuncDisableTimer)(int timerId) = 0;
	inline static void(__fastcall* FuncDoNothing)() = 0;
	inline static void(__fastcall* FuncEnableRule)(int groupId) = 0;
	inline static void(__fastcall* FuncEnableTimer)(int timerId, int timeInterval) = 0;
	inline static void(__fastcall* FuncEnableWallPlacement)(int perimeter) = 0;
	inline static void(__fastcall* FuncFeBreakPoint)(int param1, int param2, int param3, int param4) = 0;
	inline static void(__fastcall* FuncGenerateRandomNumber)(int range) = 0;
	inline static void(__fastcall* FuncLog)(int text) = 0;
	inline static void(__fastcall* FuncLogTrace)(int traceNumber) = 0;
	inline static void(__fastcall* FuncReleaseEscrow)(int resourceType) = 0;
	inline static void(__fastcall* FuncResearch)(int researchType) = 0;
	inline static void(__fastcall* FuncResign)() = 0;
	inline static void(__fastcall* FuncSellCommodity)(int commodityType) = 0;
	inline static void(__fastcall* FuncSetAuthorName)(int name) = 0;
	inline static void(__fastcall* FuncSetAuthorEmail)(int email) = 0;
	inline static void(__fastcall* FuncSetAuthorVersion)(int version) = 0;
	inline static void(__fastcall* FuncSetDifficultyParameter)(int difficultyParameter, int value) = 0;
	inline static void(__fastcall* FuncSetDoctrine)(int doctrine) = 0;
	inline static void(__fastcall* FuncSetEscrowPercentage)(int resourceType, int percentage) = 0;
	inline static void(__fastcall* FuncSetGoal)(int goalId, int goalValue) = 0;
	inline static void(__fastcall* FuncSetSharedGoal)(int goalId, int goal) = 0;
	inline static void(__fastcall* FuncSetSignal)(int signalId) = 0;
	inline static void(__fastcall* FuncSetStance)(int playerNumber, int stance) = 0;
	inline static void(__fastcall* FuncSetStrategicNumber)(int strategicNumber, int value) = 0;
	inline static void(__fastcall* FuncSkyboxClearSignal)(int param) = 0;
	inline static void(__fastcall* FuncSkyboxSetNameMode)(int param) = 0;
	inline static void(__fastcall* FuncSpy)() = 0;
	inline static void(__fastcall* FuncTaunt)(int tauntNumber) = 0;
	inline static void(__fastcall* FuncTauntUsingRange)(int tauntIdStart, int tauntIdRange) = 0;
	inline static void(__fastcall* FuncTrain)(int unitType) = 0;
	inline static void(__fastcall* FuncTributeToPlayer)(int playerNumber, int resourceType, int tributeAmount) = 0;
	inline static void(__fastcall* FuncUpAddCostData)(int goalId, int typeOp, int opValue) = 0;
	inline static void(__fastcall* FuncUpAddObjectById)(int searchSource, int typeOp, int opId) = 0;
	inline static void(__fastcall* FuncUpAddObjectCost)(int typeOp1, int objectId, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpAddPoint)(int goalPoint1, int goalPoint2, int typeOp, int count) = 0;
	inline static void(__fastcall* FuncUpAddResearchCost)(int typeOp1, int techId, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpAssignBuilders)(int typeOp1, int buildingId, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpBoundPoint)(int goalPoint1, int goalPoint2) = 0;
	inline static void(__fastcall* FuncUpBoundPrecisePoint)(int goalPoint, int precise, int typeOp, int border) = 0;
	inline static void(__fastcall* FuncUpBuild)(int placementType, int escrowState, int typeOp, int buildingId) = 0;
	inline static void(__fastcall* FuncUpBuildLine)(int goalPoint1, int goalPoint2, int typeOp, int buildingId) = 0;
	inline static void(__fastcall* FuncUpBuyCommodity)(int typeOp1, int resourceAmount, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpCcAddResource)(int typeOp1, int resourceAmount, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpCcSendCheat)(int code) = 0;
	inline static void(__fastcall* FuncUpChangeName)(int newName) = 0;
	inline static void(__fastcall* FuncUpChatDataToAll)(int format, int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpChatDataToAllUsingId)(int param1, int stringId, int param3) = 0;
	inline static void(__fastcall* FuncUpChatDataToPlayerUsingId)(int stringId, int playerId, int param3, int param4) = 0;
	inline static void(__fastcall* FuncUpChatDataToPlayer)(int player, int format, int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpChatDataToSelf)(int format, int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpCleanSearch)(int searchSource, int objectData, int searchOrder) = 0;
	inline static void(__fastcall* FuncUpCopyPoint)(int goalPoint1, int goalPoint2) = 0;
	inline static void(__fastcall* FuncUpCreateGroup)(int goalIndex, int goalCount, int typeOp, int groupId) = 0;
	inline static void(__fastcall* FuncUpCrossTiles)(int goalPoint1, int goalPoint2, int typeOp, int tiles) = 0;
	inline static void(__fastcall* FuncUpDeleteDistantFarms)(int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpDeleteIdleUnits)(int idleType) = 0;
	inline static void(__fastcall* FuncUpDeleteObjects)(int typeOp1, int unitId, int typeOp2, int hitpoints) = 0;
	inline static void(__fastcall* FuncUpDisbandGroupType)(int groupType) = 0;
	inline static void(__fastcall* FuncUpDropResources)(int resource, int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpFilterDistance)(int typeOp1, int minDistance, int typeOp2, int maxDistance) = 0;
	inline static void(__fastcall* FuncUpFilterExclude)(int cmdId, int actionId, int orderId, int classId) = 0;
	inline static void(__fastcall* FuncUpFilterGarrison)(int typeOp1, int minGarrison, int typeOp2, int maxGarrison) = 0;
	inline static void(__fastcall* FuncUpFilterInclude)(int cmdId, int actionId, int orderId, int onMainland) = 0;
	inline static void(__fastcall* FuncUpFilterRange)(int minGarrison, int maxGarrison, int minDistance, int maxDistance) = 0;
	inline static void(__fastcall* FuncUpFilterStatus)(int typeOp1, int objectStatus, int typeOp2, int objectList) = 0;
	inline static void(__fastcall* FuncUpFindFlare)(int goalPoint) = 0;
	inline static void(__fastcall* FuncUpFindLocal)(int typeOp1, int unitId, int typeOp2, int count) = 0;
	inline static void(__fastcall* FuncUpFindNextPlayer)(int playerStance, int findPlayerMethod, int goalPlayerId) = 0;
	inline static void(__fastcall* FuncUpFindPlayer)(int playerStance, int findPlayerMethod, int goalPlayerId) = 0;
	inline static void(__fastcall* FuncUpFindPlayerFlare)(int player, int goalPoint) = 0;
	inline static void(__fastcall* FuncUpFindRemote)(int typeOp1, int unitId, int typeOp2, int count) = 0;
	inline static void(__fastcall* FuncUpFindResource)(int typeOp1, int resource, int typeOp2, int count) = 0;
	inline static void(__fastcall* FuncUpFindStatusLocal)(int typeOp1, int unitId, int typeOp2, int count) = 0;
	inline static void(__fastcall* FuncUpFindStatusRemote)(int typeOp1, int unitId, int typeOp2, int count) = 0;
	inline static void(__fastcall* FuncUpFullResetSearch)() = 0;
	inline static void(__fastcall* FuncUpGarrison)(int objectId, int typeOp, int unitId) = 0;
	inline static void(__fastcall* FuncUpGatherInside)(int typeOp1, int buildingId, int typeOp2, int state) = 0;
	inline static void(__fastcall* FuncUpGetAttackerClass)(int goalSourceClass) = 0;
	inline static void(__fastcall* FuncUpGetCostDelta)(int goalId) = 0;
	inline static void(__fastcall* FuncUpGetEvent)(int typeOp, int eventId, int goalValue) = 0;
	inline static void(__fastcall* FuncUpGetFact)(int factId, int factParam, int goalId) = 0;
	inline static void(__fastcall* FuncUpGetFactMax)(int player, int factId, int param, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetFactMin)(int player, int factId, int param, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetFactSum)(int player, int factId, int param, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetFocusFact)(int factId, int param, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetGroupSize)(int typeOp, int groupId, int goalSize) = 0;
	inline static void(__fastcall* FuncUpGetGuardState)(int goalState) = 0;
	inline static void(__fastcall* FuncUpGetIndirectGoal)(int typeOp1, int goalId, int goalValue) = 0;
	inline static void(__fastcall* FuncUpGetObjectData)(int objectData, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetObjectTargetData)(int objectData, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetObjectTypeData)(int typeOp, int objectTypeId, int objectData, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetPathDistance)(int goalPoint, int strict, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetPlayerColor)(int player, int goalColorId) = 0;
	inline static void(__fastcall* FuncUpGetPlayerFact)(int player, int factId, int param, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetPoint)(int positionType, int goalPoint) = 0;
	inline static void(__fastcall* FuncUpGetPointContains)(int goalPoint, int goalId, int typeOp, int objectId) = 0;
	inline static void(__fastcall* FuncUpGetPointDistance)(int goalPoint1, int goalPoint2, int goalDistance) = 0;
	inline static void(__fastcall* FuncUpGetPointElevation)(int goalPoint, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetPointTerrain)(int goalPoint, int goalTerrain) = 0;
	inline static void(__fastcall* FuncUpGetPointZone)(int goalPoint, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetPreciseTime)(int goalStart, int goalTime) = 0;
	inline static void(__fastcall* FuncUpGetProjectilePlayer)(int projectileType, int goalPlayerId) = 0;
	inline static void(__fastcall* FuncUpGetRuleId)(int goalRuleId) = 0;
	inline static void(__fastcall* FuncUpGetSearchState)(int goalState) = 0;
	inline static void(__fastcall* FuncUpGetSharedGoal)(int typeOp, int sharedGoalId, int goalValue) = 0;
	inline static void(__fastcall* FuncUpGetSignal)(int typeOp, int signalId, int goalValue) = 0;
	inline static void(__fastcall* FuncUpGetTargetFact)(int factId, int param, int goalData) = 0;
	inline static void(__fastcall* FuncUpGetThreatData)(int goalElapsedTime, int goalPlayerId, int goalSourceClass, int goalTargetClass) = 0;
	inline static void(__fastcall* FuncUpGetTimer)(int typeOp, int timerId, int goalValue) = 0;
	inline static void(__fastcall* FuncUpGetTreatyData)(int param) = 0;
	inline static void(__fastcall* FuncUpGetUpgradeId)(int player, int count, int goalTypeId, int goalUpgradeId) = 0;
	inline static void(__fastcall* FuncUpGetVictoryData)(int goalPlayerId, int goalType, int goalTime) = 0;
	inline static void(__fastcall* FuncUpGetVictoryLimit)(int goalLimit) = 0;
	inline static void(__fastcall* FuncUpGuardUnit)(int objectId, int typeOp, int unitId) = 0;
	inline static void(__fastcall* FuncUpJumpDirect)(int typeOp, int ruleId) = 0;
	inline static void(__fastcall* FuncUpJumpDynamic)(int typeOp, int ruleDelta) = 0;
	inline static void(__fastcall* FuncUpJumpRule)(int ruleDelta) = 0;
	inline static void(__fastcall* FuncUpLerpPercent)(int goalPoint1, int goalPoint2, int typeOp, int percent) = 0;
	inline static void(__fastcall* FuncUpLerpTiles)(int goalPoint1, int goalPoint2, int typeOp, int tiles) = 0;
	inline static void(__fastcall* FuncUpLogData)(int plain, int format, int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpModifyEscrow)(int resource, int mathOp, int value) = 0;
	inline static void(__fastcall* FuncUpModifyFlag)(int goalId, int mathOp, int value) = 0;
	inline static void(__fastcall* FuncUpModifyGoal)(int goalId, int mathOp, int value) = 0;
	inline static void(__fastcall* FuncUpModifyGroupFlag)(int on, int typeOp, int groupId) = 0;
	inline static void(__fastcall* FuncUpModifySn)(int snId, int mathOp, int value) = 0;
	inline static void(__fastcall* FuncUpReleaseEscrow)() = 0;
	inline static void(__fastcall* FuncUpRemoveObjects)(int searchSource, int objectData, int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpRequestHunters)(int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpResearch)(int escrowState, int typeOp, int techId) = 0;
	inline static void(__fastcall* FuncUpResetAttackNow)() = 0;
	inline static void(__fastcall* FuncUpResetBuilding)(int preserveResearch, int typeOp, int buildingId) = 0;
	inline static void(__fastcall* FuncUpResetCostData)(int goalId) = 0;
	inline static void(__fastcall* FuncUpResetFilters)() = 0;
	inline static void(__fastcall* FuncUpResetGroup)(int typeOp, int groupId) = 0;
	inline static void(__fastcall* FuncUpResetPlacement)(int typeOp, int buildingId) = 0;
	inline static void(__fastcall* FuncUpResetScouts)() = 0;
	inline static void(__fastcall* FuncUpResetSearch)(int localIndex, int localList, int remoteIndex, int remoteList) = 0;
	inline static void(__fastcall* FuncUpResetTargetPriorities)(int priorityType, int mode) = 0;
	inline static void(__fastcall* FuncUpResetUnit)(int typeOp, int unitId) = 0;
	inline static void(__fastcall* FuncUpRetaskGatherers)(int resource, int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpRetreatNow)() = 0;
	inline static void(__fastcall* FuncUpRetreatTo)(int objectId, int typeOp, int unitId) = 0;
	inline static void(__fastcall* FuncUpSellCommodity)(int typeOp1, int resourceAmount, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpSendFlare)(int goalPoint) = 0;
	inline static void(__fastcall* FuncUpSendScout)(int groupType, int positionType) = 0;
	inline static void(__fastcall* FuncUpSetAttackStance)(int unitId, int typeOp, int attackStance) = 0;
	inline static void(__fastcall* FuncUpSetDefensePriority)(int typeOp1, int buildingId, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpSetEvent)(int typeOp1, int eventId, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpSetGroup)(int searchSource, int typeOp, int groupId) = 0;
	inline static void(__fastcall* FuncUpSetIndirectGoal)(int typeOp1, int goalId, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpSetOffensePriority)(int typeOp1, int objectId, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpSetPlacementData)(int playerAlly, int objectId, int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpSetPreciseTargetPoint)(int goalPoint) = 0;
	inline static void(__fastcall* FuncUpSetSharedGoal)(int typeOp1, int sharedGoalId, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpSetSignal)(int typeOp1, int signalId, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpSetTargetById)(int typeOp, int id) = 0;
	inline static void(__fastcall* FuncUpSetTargetObject)(int searchSource, int typeOp, int index) = 0;
	inline static void(__fastcall* FuncUpSetTargetPoint)(int goalPoint) = 0;
	inline static void(__fastcall* FuncUpSetTimer)(int typeOp1, int timerId, int typeOp2, int value) = 0;
	inline static void(__fastcall* FuncUpSetupCostData)(int resetCost, int goalId) = 0;
	inline static void(__fastcall* FuncUpStoreMapName)(int extension) = 0;
	inline static void(__fastcall* FuncUpStoreObjectName)() = 0;
	inline static void(__fastcall* FuncUpStorePlayerChat)(int player) = 0;
	inline static void(__fastcall* FuncUpStorePlayerName)(int player) = 0;
	inline static void(__fastcall* FuncUpStoreTechName)(int typeOp, int techId) = 0;
	inline static void(__fastcall* FuncUpStoreText)(int typeOp, int languageId) = 0;
	inline static void(__fastcall* FuncUpStoreTypeName)(int typeOp, int objectTypeId) = 0;
	inline static void(__fastcall* FuncUpTargetObjects)(int target, int action, int formation, int attackStance) = 0;
	inline static void(__fastcall* FuncUpTargetPoint)(int goalPoint, int action, int formation, int attackStance) = 0;
	inline static void(__fastcall* FuncUpTestharnessReport)(int param1, int param2, int param3) = 0;
	inline static void(__fastcall* FuncUpTestharnessTest)(int param1, int param2, int param3, int param4) = 0;
	inline static void(__fastcall* FuncUpTrain)(int escrowState, int typeOp, int unitId) = 0;
	inline static void(__fastcall* FuncUpTributeToPlayer)(int player, int resourceAmount, int typeOp, int value) = 0;
	inline static void(__fastcall* FuncUpUngarrison)(int typeOp, int objectId) = 0;
	inline static void(__fastcall* FuncUpUpdateTargets)() = 0;
};
