#pragma once
#include <stdint.h>

#include "misc/Configuration.h"

class ExpertAction
{
public:
	static void UpdateAddresses();

	static void AcknowledgeEvent(int eventType, int id);
	static void AcknowledgeTaunt(int playerNumber, int tauntId);
	static void AttackNow();
	static void Build(int buildingType);
	static void BuildForward(int buildingType);
	static void BuildGate(int perimeter);
	static void BuildWall(int perimeter, int wallType);
	static void BuyCommodity(int commodityType);
	static void CcAddResource(int resourceType, int amount);
	static void ChatLocal(int text);
	static void ChatLocalUsingId(int stringId);
	static void ChatLocalUsingRange(int stringIdStart, int stringIdRange);
	static void ChatLocalToSelf(int text);
	static void ChatToAll(int text);
	static void ChatToAllUsingId(int stringId);
	static void ChatToAllUsingRange(int stringIdStart, int stringIdRange);
	static void ChatToAllies(int text);
	static void ChatToAlliesUsingId(int stringId);
	static void ChatToAlliesUsingRange(int stringIdStart, int stringIdRange);
	static void ChatToEnemies(int text);
	static void ChatToEnemiesUsingId(int stringId);
	static void ChatToEnemiesUsingRange(int stringIdStart, int stringIdRange);
	static void ChatToPlayer(int playerNumber, int text);
	static void ChatToPlayerUsingId(int playerNumber, int stringId);
	static void ChatToPlayerUsingRange(int playerNumber, int stringIdStart, int stringIdRange);
	static void ChatTrace(int traceNumber);
	static void ClearTributeMemory(int playerNumber, int resourceType);
	static void DeleteBuilding(int buildingType);
	static void DeleteUnit(int unitType);
	static void DisableRule(int groupId);
	static void DisableSelf();
	static void DisableTimer(int timerId);
	static void DoNothing();
	static void EnableRule(int groupId);
	static void EnableTimer(int timerId, int timeInterval);
	static void EnableWallPlacement(int perimeter);
	static void GenerateRandomNumber(int range);
	static void Log(int text);
	static void LogTrace(int traceNumber);
	static void ReleaseEscrow(int resourceType);
	static void Research(int researchType);
	static void Resign();
	static void SellCommodity(int commodityType);
	static void SetAuthorName(int name);
	static void SetAuthorEmail(int email);
	static void SetAuthorVersion(int version);
	static void SetDifficultyParameter(int difficultyParameter, int value);
	static void SetDoctrine(int doctrine);
	static void SetEscrowPercentage(int resourceType, int percentage);
	static void SetGoal(int goalId, int goalValue);
	static void SetSharedGoal(int goalId, int goal);
	static void SetSignal(int signalId);
	static void SetStance(int playerNumber, int stance);
	static void SetStrategicNumber(int strategicNumber, int value);
	static void Spy();
	static void Taunt(int tauntNumber);
	static void TauntUsingRange(int tauntIdStart, int tauntIdRange);
	static void Train(int unitType);
	static void TributeToPlayer(int playerNumber, int resourceType, int tributeAmount);
	static void UpAddCostData(int goalId, int typeOp, int opValue);
	static void UpAddObjectById(int searchSource, int typeOp, int opId);
	static void UpAddObjectCost(int typeOp1, int objectId, int typeOp2, int value);
	static void UpAddPoint(int goalPoint1, int goalPoint2, int typeOp, int count);
	static void UpAddResearchCost(int typeOp1, int techId, int typeOp2, int value);
	static void UpAssignBuilders(int typeOp1, int buildingId, int typeOp2, int value);
	static void UpBoundPoint(int goalPoint1, int goalPoint2);
	static void UpBoundPrecisePoint(int goalPoint, int precise, int typeOp, int border);
	static void UpBuild(int placementType, int escrowState, int typeOp, int buildingId);
	static void UpBuildLine(int goalPoint1, int goalPoint2, int typeOp, int buildingId);
	static void UpBuyCommodity(int typeOp1, int resourceAmount, int typeOp2, int value);
	static void UpCcAddResource(int typeOp1, int resourceAmount, int typeOp2, int value);
	static void UpCcSendCheat(int code);
	static void UpChangeName(int newName);
	static void UpChatDataToAll(int format, int typeOp, int value);
	static void UpChatDataToPlayer(int player, int format, int typeOp, int value);
	static void UpChatDataToSelf(int format, int typeOp, int value);
	static void UpCleanSearch(int searchSource, int objectData, int searchOrder);
	static void UpCopyPoint(int goalPoint1, int goalPoint2);
	static void UpCreateGroup(int goalIndex, int goalCount, int typeOp, int groupId);
	static void UpCrossTiles(int goalPoint1, int goalPoint2, int typeOp, int tiles);
	static void UpDeleteDistantFarms(int typeOp, int value);
	static void UpDeleteIdleUnits(int idleType);
	static void UpDeleteObjects(int typeOp1, int unitId, int typeOp2, int hitpoints);
	static void UpDisbandGroupType(int groupType);
	static void UpDropResources(int resource, int typeOp, int value);
	static void UpFilterDistance(int typeOp1, int minDistance, int typeOp2, int maxDistance);
	static void UpFilterExclude(int cmdId, int actionId, int orderId, int classId);
	static void UpFilterGarrison(int typeOp1, int minGarrison, int typeOp2, int maxGarrison);
	static void UpFilterInclude(int cmdId, int actionId, int orderId, int onMainland);
	static void UpFilterRange(int minGarrison, int maxGarrison, int minDistance, int maxDistance);
	static void UpFilterStatus(int typeOp1, int objectStatus, int typeOp2, int objectList);
	static void UpFindFlare(int goalPoint);
	static void UpFindLocal(int typeOp1, int unitId, int typeOp2, int count);
	static void UpFindNextPlayer(int playerStance, int findPlayerMethod, int goalPlayerId);
	static void UpFindPlayer(int playerStance, int findPlayerMethod, int goalPlayerId);
	static void UpFindPlayerFlare(int player, int goalPoint);
	static void UpFindRemote(int typeOp1, int unitId, int typeOp2, int count);
	static void UpFindResource(int typeOp1, int resource, int typeOp2, int count);
	static void UpFindStatusLocal(int typeOp1, int unitId, int typeOp2, int count);
	static void UpFindStatusRemote(int typeOp1, int unitId, int typeOp2, int count);
	static void UpFullResetSearch();
	static void UpGarrison(int objectId, int typeOp, int unitId);
	static void UpGatherInside(int typeOp1, int buildingId, int typeOp2, int state);
	static void UpGetAttackerClass(int goalSourceClass);
	static void UpGetCostDelta(int goalId);
	static void UpGetEvent(int typeOp, int eventId, int goalValue);
	static void UpGetFact(int factId, int factParam, int goalId);
	static void UpGetFactMax(int player, int factId, int param, int goalData);
	static void UpGetFactMin(int player, int factId, int param, int goalData);
	static void UpGetFactSum(int player, int factId, int param, int goalData);
	static void UpGetFocusFact(int factId, int param, int goalData);
	static void UpGetGroupSize(int typeOp, int groupId, int goalSize);
	static void UpGetIndirectGoal(int typeOp1, int goalId, int goalValue);
	static void UpGetObjectData(int objectData, int goalData);
	static void UpGetObjectTargetData(int objectData, int goalData);
	static void UpGetObjectTypeData(int typeOp, int objectTypeId, int objectData, int goalData);
	static void UpGetPathDistance(int goalPoint, int strict, int goalData);
	static void UpGetPlayerColor(int player, int goalColorId);
	static void UpGetPlayerFact(int player, int factId, int param, int goalData);
	static void UpGetPoint(int positionType, int goalPoint);
	static void UpGetPointContains(int goalPoint, int goalId, int typeOp, int objectId);
	static void UpGetPointDistance(int goalPoint1, int goalPoint2, int goalDistance);
	static void UpGetPointElevation(int goalPoint, int goalData);
	static void UpGetPointTerrain(int goalPoint, int goalTerrain);
	static void UpGetPointZone(int goalPoint, int goalData);
	static void UpGetPreciseTime(int goalStart, int goalTime);
	static void UpGetProjectilePlayer(int projectileType, int goalPlayerId);
	static void UpGetRuleId(int goalRuleId);
	static void UpGetSearchState(int goalState);
	static void UpGetSharedGoal(int typeOp, int sharedGoalId, int goalValue);
	static void UpGetSignal(int typeOp, int signalId, int goalValue);
	static void UpGetTargetFact(int factId, int param, int goalData);
	static void UpGetThreatData(int goalElapsedTime, int goalPlayerId, int goalSourceClass, int goalTargetClass);
	static void UpGetTimer(int typeOp, int timerId, int goalValue);
	static void UpGetVictoryData(int goalPlayerId, int goalType, int goalTime);
	static void UpGetVictoryLimit(int goalLimit);
	static void UpGuardUnit(int objectId, int typeOp, int unitId);
	static void UpJumpDirect(int typeOp, int ruleId);
	static void UpJumpDynamic(int typeOp, int ruleDelta);
	static void UpJumpRule(int ruleDelta);
	static void UpLerpPercent(int goalPoint1, int goalPoint2, int typeOp, int percent);
	static void UpLerpTiles(int goalPoint1, int goalPoint2, int typeOp, int tiles);
	static void UpLogData(int plain, int format, int typeOp, int value);
	static void UpModifyEscrow(int resource, int mathOp, int value);
	static void UpModifyFlag(int goalId, int mathOp, int value);
	static void UpModifyGoal(int goalId, int mathOp, int value);
	static void UpModifyGroupFlag(int on, int typeOp, int groupId);
	static void UpModifySn(int snId, int mathOp, int value);
	static void UpReleaseEscrow();
	static void UpRemoveObjects(int searchSource, int objectData, int typeOp, int value);
	static void UpRequestHunters(int typeOp, int value);
	static void UpResearch(int escrowState, int typeOp, int techId);
	static void UpResetAttackNow();
	static void UpResetBuilding(int preserveResearch, int typeOp, int buildingId);
	static void UpResetCostData(int goalId);
	static void UpResetFilters();
	static void UpResetGroup(int typeOp, int groupId);
	static void UpResetPlacement(int typeOp, int buildingId);
	static void UpResetScouts();
	static void UpResetSearch(int localIndex, int localList, int remoteIndex, int remoteList);
	static void UpResetTargetPriorities(int priorityType, int mode);
	static void UpResetUnit(int typeOp, int unitId);
	static void UpRetaskGatherers(int resource, int typeOp, int value);
	static void UpRetreatNow();
	static void UpRetreatTo(int objectId, int typeOp, int unitId);
	static void UpSellCommodity(int typeOp1, int resourceAmount, int typeOp2, int value);
	static void UpSendFlare(int goalPoint);
	static void UpSendScout(int groupType, int positionType);
	static void UpSetAttackStance(int unitId, int typeOp, int attackStance);
	static void UpSetDefensePriority(int typeOp1, int buildingId, int typeOp2, int value);
	static void UpSetEvent(int typeOp1, int eventId, int typeOp2, int value);
	static void UpSetGroup(int searchSource, int typeOp, int groupId);
	static void UpSetIndirectGoal(int typeOp1, int goalId, int typeOp2, int value);
	static void UpSetOffensePriority(int typeOp1, int objectId, int typeOp2, int value);
	static void UpSetPlacementData(int playerAlly, int objectId, int typeOp, int value);
	static void UpSetPreciseTargetPoint(int goalPoint);
	static void UpSetSharedGoal(int typeOp1, int sharedGoalId, int typeOp2, int value);
	static void UpSetSignal(int typeOp1, int signalId, int typeOp2, int value);
	static void UpSetTargetById(int typeOp, int id);
	static void UpSetTargetObject(int searchSource, int typeOp, int index);
	static void UpSetTargetPoint(int goalPoint);
	static void UpSetTimer(int typeOp1, int timerId, int typeOp2, int value);
	static void UpSetupCostData(int resetCost, int goalId);
	static void UpStoreMapName(int extension);
	static void UpStoreObjectName();
	static void UpStorePlayerChat(int player);
	static void UpStorePlayerName(int player);
	static void UpStoreTechName(int typeOp, int techId);
	static void UpStoreText(int typeOp, int languageId);
	static void UpStoreTypeName(int typeOp, int objectTypeId);
	static void UpTargetObjects(int target, int action, int formation, int attackStance);
	static void UpTargetPoint(int goalPoint, int action, int formation, int attackStance);
	static void UpTrain(int escrowState, int typeOp, int unitId);
	static void UpTributeToPlayer(int player, int resourceAmount, int typeOp, int value);
	static void UpUngarrison(int typeOp, int objectId);
	static void UpUpdateTargets();
#if defined GAME_DE
	static void ChatDebug(int text);
	static void FeBreakPoint(int param1, int param2, int param3, int param4);
	static void SkyboxClearSignal(int param);
	static void SkyboxSetNameMode(int param);
	static void UpChatDataToAllUsingId(int param1, int stringId, int param3);
	static void UpChatDataToPlayerUsingId(int stringId, int playerId, int param3, int param4);
	static void UpGetTreatyData(int param);
	static void UpTestharnessReport(int param1, int param2, int param3);
	static void UpTestharnessTest(int param1, int param2, int param3, int param4);
#elif defined GAME_AOC
	static void UpGetAlliedTarget(int param1, int param2);
	static void UpGetGuardState(int goalState);
	static void UpGetUpgradeId(int player, int count, int goalTypeId, int goalUpgradeId);
	static void UpOutOfSync();
#endif

private:
	ExpertAction() {};

	inline static void(*FuncAcknowledgeEvent)(int eventType, int id) = 0;
	inline static void(*FuncAcknowledgeTaunt)(int playerNumber, int tauntId) = 0;
	inline static void(*FuncAttackNow)() = 0;
	inline static void(*FuncBuild)(int buildingType) = 0;
	inline static void(*FuncBuildForward)(int buildingType) = 0;
	inline static void(*FuncBuildGate)(int perimeter) = 0;
	inline static void(*FuncBuildWall)(int perimeter, int wallType) = 0;
	inline static void(*FuncBuyCommodity)(int commodityType) = 0;
	inline static void(*FuncCcAddResource)(int resourceType, int amount) = 0;
	inline static void(*FuncChatLocal)(int text) = 0;
	inline static void(*FuncChatLocalUsingId)(int stringId) = 0;
	inline static void(*FuncChatLocalUsingRange)(int stringIdStart, int stringIdRange) = 0;
	inline static void(*FuncChatLocalToSelf)(int text) = 0;
	inline static void(*FuncChatToAll)(int text) = 0;
	inline static void(*FuncChatToAllUsingId)(int stringId) = 0;
	inline static void(*FuncChatToAllUsingRange)(int stringIdStart, int stringIdRange) = 0;
	inline static void(*FuncChatToAllies)(int text) = 0;
	inline static void(*FuncChatToAlliesUsingId)(int stringId) = 0;
	inline static void(*FuncChatToAlliesUsingRange)(int stringIdStart, int stringIdRange) = 0;
	inline static void(*FuncChatToEnemies)(int text) = 0;
	inline static void(*FuncChatToEnemiesUsingId)(int stringId) = 0;
	inline static void(*FuncChatToEnemiesUsingRange)(int stringIdStart, int stringIdRange) = 0;
	inline static void(*FuncChatToPlayer)(int playerNumber, int text) = 0;
	inline static void(*FuncChatToPlayerUsingId)(int playerNumber, int stringId) = 0;
	inline static void(*FuncChatToPlayerUsingRange)(int playerNumber, int stringIdStart, int stringIdRange) = 0;
	inline static void(*FuncChatTrace)(int traceNumber) = 0;
	inline static void(*FuncClearTributeMemory)(int playerNumber, int resourceType) = 0;
	inline static void(*FuncDeleteBuilding)(int buildingType) = 0;
	inline static void(*FuncDeleteUnit)(int unitType) = 0;
	inline static void(*FuncDisableRule)(int groupId) = 0;
	inline static void(*FuncDisableSelf)() = 0;
	inline static void(*FuncDisableTimer)(int timerId) = 0;
	inline static void(*FuncDoNothing)() = 0;
	inline static void(*FuncEnableRule)(int groupId) = 0;
	inline static void(*FuncEnableTimer)(int timerId, int timeInterval) = 0;
	inline static void(*FuncEnableWallPlacement)(int perimeter) = 0;
	inline static void(*FuncGenerateRandomNumber)(int range) = 0;
	inline static void(*FuncLog)(int text) = 0;
	inline static void(*FuncLogTrace)(int traceNumber) = 0;
	inline static void(*FuncReleaseEscrow)(int resourceType) = 0;
	inline static void(*FuncResearch)(int researchType) = 0;
	inline static void(*FuncResign)() = 0;
	inline static void(*FuncSellCommodity)(int commodityType) = 0;
	inline static void(*FuncSetAuthorName)(int name) = 0;
	inline static void(*FuncSetAuthorEmail)(int email) = 0;
	inline static void(*FuncSetAuthorVersion)(int version) = 0;
	inline static void(*FuncSetDifficultyParameter)(int difficultyParameter, int value) = 0;
	inline static void(*FuncSetDoctrine)(int doctrine) = 0;
	inline static void(*FuncSetEscrowPercentage)(int resourceType, int percentage) = 0;
	inline static void(*FuncSetGoal)(int goalId, int goalValue) = 0;
	inline static void(*FuncSetSharedGoal)(int goalId, int goal) = 0;
	inline static void(*FuncSetSignal)(int signalId) = 0;
	inline static void(*FuncSetStance)(int playerNumber, int stance) = 0;
	inline static void(*FuncSetStrategicNumber)(int strategicNumber, int value) = 0;
	inline static void(*FuncSpy)() = 0;
	inline static void(*FuncTaunt)(int tauntNumber) = 0;
	inline static void(*FuncTauntUsingRange)(int tauntIdStart, int tauntIdRange) = 0;
	inline static void(*FuncTrain)(int unitType) = 0;
	inline static void(*FuncTributeToPlayer)(int playerNumber, int resourceType, int tributeAmount) = 0;
	inline static void(*FuncUpAddCostData)(int goalId, int typeOp, int opValue) = 0;
	inline static void(*FuncUpAddObjectById)(int searchSource, int typeOp, int opId) = 0;
	inline static void(*FuncUpAddObjectCost)(int typeOp1, int objectId, int typeOp2, int value) = 0;
	inline static void(*FuncUpAddPoint)(int goalPoint1, int goalPoint2, int typeOp, int count) = 0;
	inline static void(*FuncUpAddResearchCost)(int typeOp1, int techId, int typeOp2, int value) = 0;
	inline static void(*FuncUpAssignBuilders)(int typeOp1, int buildingId, int typeOp2, int value) = 0;
	inline static void(*FuncUpBoundPoint)(int goalPoint1, int goalPoint2) = 0;
	inline static void(*FuncUpBoundPrecisePoint)(int goalPoint, int precise, int typeOp, int border) = 0;
	inline static void(*FuncUpBuild)(int placementType, int escrowState, int typeOp, int buildingId) = 0;
	inline static void(*FuncUpBuildLine)(int goalPoint1, int goalPoint2, int typeOp, int buildingId) = 0;
	inline static void(*FuncUpBuyCommodity)(int typeOp1, int resourceAmount, int typeOp2, int value) = 0;
	inline static void(*FuncUpCcAddResource)(int typeOp1, int resourceAmount, int typeOp2, int value) = 0;
	inline static void(*FuncUpCcSendCheat)(int code) = 0;
	inline static void(*FuncUpChangeName)(int newName) = 0;
	inline static void(*FuncUpChatDataToAll)(int format, int typeOp, int value) = 0;
	inline static void(*FuncUpChatDataToPlayer)(int player, int format, int typeOp, int value) = 0;
	inline static void(*FuncUpChatDataToSelf)(int format, int typeOp, int value) = 0;
	inline static void(*FuncUpCleanSearch)(int searchSource, int objectData, int searchOrder) = 0;
	inline static void(*FuncUpCopyPoint)(int goalPoint1, int goalPoint2) = 0;
	inline static void(*FuncUpCreateGroup)(int goalIndex, int goalCount, int typeOp, int groupId) = 0;
	inline static void(*FuncUpCrossTiles)(int goalPoint1, int goalPoint2, int typeOp, int tiles) = 0;
	inline static void(*FuncUpDeleteDistantFarms)(int typeOp, int value) = 0;
	inline static void(*FuncUpDeleteIdleUnits)(int idleType) = 0;
	inline static void(*FuncUpDeleteObjects)(int typeOp1, int unitId, int typeOp2, int hitpoints) = 0;
	inline static void(*FuncUpDisbandGroupType)(int groupType) = 0;
	inline static void(*FuncUpDropResources)(int resource, int typeOp, int value) = 0;
	inline static void(*FuncUpFilterDistance)(int typeOp1, int minDistance, int typeOp2, int maxDistance) = 0;
	inline static void(*FuncUpFilterExclude)(int cmdId, int actionId, int orderId, int classId) = 0;
	inline static void(*FuncUpFilterGarrison)(int typeOp1, int minGarrison, int typeOp2, int maxGarrison) = 0;
	inline static void(*FuncUpFilterInclude)(int cmdId, int actionId, int orderId, int onMainland) = 0;
	inline static void(*FuncUpFilterRange)(int minGarrison, int maxGarrison, int minDistance, int maxDistance) = 0;
	inline static void(*FuncUpFilterStatus)(int typeOp1, int objectStatus, int typeOp2, int objectList) = 0;
	inline static void(*FuncUpFindFlare)(int goalPoint) = 0;
	inline static void(*FuncUpFindLocal)(int typeOp1, int unitId, int typeOp2, int count) = 0;
	inline static void(*FuncUpFindNextPlayer)(int playerStance, int findPlayerMethod, int goalPlayerId) = 0;
	inline static void(*FuncUpFindPlayer)(int playerStance, int findPlayerMethod, int goalPlayerId) = 0;
	inline static void(*FuncUpFindPlayerFlare)(int player, int goalPoint) = 0;
	inline static void(*FuncUpFindRemote)(int typeOp1, int unitId, int typeOp2, int count) = 0;
	inline static void(*FuncUpFindResource)(int typeOp1, int resource, int typeOp2, int count) = 0;
	inline static void(*FuncUpFindStatusLocal)(int typeOp1, int unitId, int typeOp2, int count) = 0;
	inline static void(*FuncUpFindStatusRemote)(int typeOp1, int unitId, int typeOp2, int count) = 0;
	inline static void(*FuncUpFullResetSearch)() = 0;
	inline static void(*FuncUpGarrison)(int objectId, int typeOp, int unitId) = 0;
	inline static void(*FuncUpGatherInside)(int typeOp1, int buildingId, int typeOp2, int state) = 0;
	inline static void(*FuncUpGetAttackerClass)(int goalSourceClass) = 0;
	inline static void(*FuncUpGetCostDelta)(int goalId) = 0;
	inline static void(*FuncUpGetEvent)(int typeOp, int eventId, int goalValue) = 0;
	inline static void(*FuncUpGetFact)(int factId, int factParam, int goalId) = 0;
	inline static void(*FuncUpGetFactMax)(int player, int factId, int param, int goalData) = 0;
	inline static void(*FuncUpGetFactMin)(int player, int factId, int param, int goalData) = 0;
	inline static void(*FuncUpGetFactSum)(int player, int factId, int param, int goalData) = 0;
	inline static void(*FuncUpGetFocusFact)(int factId, int param, int goalData) = 0;
	inline static void(*FuncUpGetGroupSize)(int typeOp, int groupId, int goalSize) = 0;
	inline static void(*FuncUpGetIndirectGoal)(int typeOp1, int goalId, int goalValue) = 0;
	inline static void(*FuncUpGetObjectData)(int objectData, int goalData) = 0;
	inline static void(*FuncUpGetObjectTargetData)(int objectData, int goalData) = 0;
	inline static void(*FuncUpGetObjectTypeData)(int typeOp, int objectTypeId, int objectData, int goalData) = 0;
	inline static void(*FuncUpGetPathDistance)(int goalPoint, int strict, int goalData) = 0;
	inline static void(*FuncUpGetPlayerColor)(int player, int goalColorId) = 0;
	inline static void(*FuncUpGetPlayerFact)(int player, int factId, int param, int goalData) = 0;
	inline static void(*FuncUpGetPoint)(int positionType, int goalPoint) = 0;
	inline static void(*FuncUpGetPointContains)(int goalPoint, int goalId, int typeOp, int objectId) = 0;
	inline static void(*FuncUpGetPointDistance)(int goalPoint1, int goalPoint2, int goalDistance) = 0;
	inline static void(*FuncUpGetPointElevation)(int goalPoint, int goalData) = 0;
	inline static void(*FuncUpGetPointTerrain)(int goalPoint, int goalTerrain) = 0;
	inline static void(*FuncUpGetPointZone)(int goalPoint, int goalData) = 0;
	inline static void(*FuncUpGetPreciseTime)(int goalStart, int goalTime) = 0;
	inline static void(*FuncUpGetProjectilePlayer)(int projectileType, int goalPlayerId) = 0;
	inline static void(*FuncUpGetRuleId)(int goalRuleId) = 0;
	inline static void(*FuncUpGetSearchState)(int goalState) = 0;
	inline static void(*FuncUpGetSharedGoal)(int typeOp, int sharedGoalId, int goalValue) = 0;
	inline static void(*FuncUpGetSignal)(int typeOp, int signalId, int goalValue) = 0;
	inline static void(*FuncUpGetTargetFact)(int factId, int param, int goalData) = 0;
	inline static void(*FuncUpGetThreatData)(int goalElapsedTime, int goalPlayerId, int goalSourceClass, int goalTargetClass) = 0;
	inline static void(*FuncUpGetTimer)(int typeOp, int timerId, int goalValue) = 0;
	inline static void(*FuncUpGetVictoryData)(int goalPlayerId, int goalType, int goalTime) = 0;
	inline static void(*FuncUpGetVictoryLimit)(int goalLimit) = 0;
	inline static void(*FuncUpGuardUnit)(int objectId, int typeOp, int unitId) = 0;
	inline static void(*FuncUpJumpDirect)(int typeOp, int ruleId) = 0;
	inline static void(*FuncUpJumpDynamic)(int typeOp, int ruleDelta) = 0;
	inline static void(*FuncUpJumpRule)(int ruleDelta) = 0;
	inline static void(*FuncUpLerpPercent)(int goalPoint1, int goalPoint2, int typeOp, int percent) = 0;
	inline static void(*FuncUpLerpTiles)(int goalPoint1, int goalPoint2, int typeOp, int tiles) = 0;
	inline static void(*FuncUpLogData)(int plain, int format, int typeOp, int value) = 0;
	inline static void(*FuncUpModifyEscrow)(int resource, int mathOp, int value) = 0;
	inline static void(*FuncUpModifyFlag)(int goalId, int mathOp, int value) = 0;
	inline static void(*FuncUpModifyGoal)(int goalId, int mathOp, int value) = 0;
	inline static void(*FuncUpModifyGroupFlag)(int on, int typeOp, int groupId) = 0;
	inline static void(*FuncUpModifySn)(int snId, int mathOp, int value) = 0;
	inline static void(*FuncUpReleaseEscrow)() = 0;
	inline static void(*FuncUpRemoveObjects)(int searchSource, int objectData, int typeOp, int value) = 0;
	inline static void(*FuncUpRequestHunters)(int typeOp, int value) = 0;
	inline static void(*FuncUpResearch)(int escrowState, int typeOp, int techId) = 0;
	inline static void(*FuncUpResetAttackNow)() = 0;
	inline static void(*FuncUpResetBuilding)(int preserveResearch, int typeOp, int buildingId) = 0;
	inline static void(*FuncUpResetCostData)(int goalId) = 0;
	inline static void(*FuncUpResetFilters)() = 0;
	inline static void(*FuncUpResetGroup)(int typeOp, int groupId) = 0;
	inline static void(*FuncUpResetPlacement)(int typeOp, int buildingId) = 0;
	inline static void(*FuncUpResetScouts)() = 0;
	inline static void(*FuncUpResetSearch)(int localIndex, int localList, int remoteIndex, int remoteList) = 0;
	inline static void(*FuncUpResetTargetPriorities)(int priorityType, int mode) = 0;
	inline static void(*FuncUpResetUnit)(int typeOp, int unitId) = 0;
	inline static void(*FuncUpRetaskGatherers)(int resource, int typeOp, int value) = 0;
	inline static void(*FuncUpRetreatNow)() = 0;
	inline static void(*FuncUpRetreatTo)(int objectId, int typeOp, int unitId) = 0;
	inline static void(*FuncUpSellCommodity)(int typeOp1, int resourceAmount, int typeOp2, int value) = 0;
	inline static void(*FuncUpSendFlare)(int goalPoint) = 0;
	inline static void(*FuncUpSendScout)(int groupType, int positionType) = 0;
	inline static void(*FuncUpSetAttackStance)(int unitId, int typeOp, int attackStance) = 0;
	inline static void(*FuncUpSetDefensePriority)(int typeOp1, int buildingId, int typeOp2, int value) = 0;
	inline static void(*FuncUpSetEvent)(int typeOp1, int eventId, int typeOp2, int value) = 0;
	inline static void(*FuncUpSetGroup)(int searchSource, int typeOp, int groupId) = 0;
	inline static void(*FuncUpSetIndirectGoal)(int typeOp1, int goalId, int typeOp2, int value) = 0;
	inline static void(*FuncUpSetOffensePriority)(int typeOp1, int objectId, int typeOp2, int value) = 0;
	inline static void(*FuncUpSetPlacementData)(int playerAlly, int objectId, int typeOp, int value) = 0;
	inline static void(*FuncUpSetPreciseTargetPoint)(int goalPoint) = 0;
	inline static void(*FuncUpSetSharedGoal)(int typeOp1, int sharedGoalId, int typeOp2, int value) = 0;
	inline static void(*FuncUpSetSignal)(int typeOp1, int signalId, int typeOp2, int value) = 0;
	inline static void(*FuncUpSetTargetById)(int typeOp, int id) = 0;
	inline static void(*FuncUpSetTargetObject)(int searchSource, int typeOp, int index) = 0;
	inline static void(*FuncUpSetTargetPoint)(int goalPoint) = 0;
	inline static void(*FuncUpSetTimer)(int typeOp1, int timerId, int typeOp2, int value) = 0;
	inline static void(*FuncUpSetupCostData)(int resetCost, int goalId) = 0;
	inline static void(*FuncUpStoreMapName)(int extension) = 0;
	inline static void(*FuncUpStoreObjectName)() = 0;
	inline static void(*FuncUpStorePlayerChat)(int player) = 0;
	inline static void(*FuncUpStorePlayerName)(int player) = 0;
	inline static void(*FuncUpStoreTechName)(int typeOp, int techId) = 0;
	inline static void(*FuncUpStoreText)(int typeOp, int languageId) = 0;
	inline static void(*FuncUpStoreTypeName)(int typeOp, int objectTypeId) = 0;
	inline static void(*FuncUpTargetObjects)(int target, int action, int formation, int attackStance) = 0;
	inline static void(*FuncUpTargetPoint)(int goalPoint, int action, int formation, int attackStance) = 0;
	inline static void(*FuncUpTrain)(int escrowState, int typeOp, int unitId) = 0;
	inline static void(*FuncUpTributeToPlayer)(int player, int resourceAmount, int typeOp, int value) = 0;
	inline static void(*FuncUpUngarrison)(int typeOp, int objectId) = 0;
	inline static void(*FuncUpUpdateTargets)() = 0;
#if defined GAME_DE
	inline static void(*FuncChatDebug)(int text) = 0;
	inline static void(*FuncFeBreakPoint)(int param1, int param2, int param3, int param4) = 0;
	inline static void(*FuncSkyboxClearSignal)(int param) = 0;
	inline static void(*FuncSkyboxSetNameMode)(int param) = 0;
	inline static void(*FuncUpChatDataToAllUsingId)(int param1, int stringId, int param3) = 0;
	inline static void(*FuncUpChatDataToPlayerUsingId)(int stringId, int playerId, int param3, int param4) = 0;
	inline static void(*FuncUpGetTreatyData)(int param) = 0;
	inline static void(*FuncUpTestharnessReport)(int param1, int param2, int param3) = 0;
	inline static void(*FuncUpTestharnessTest)(int param1, int param2, int param3, int param4) = 0;
#elif defined GAME_AOC
	inline static void(*FuncUpGetAlliedTarget)(int param1, int param2) = 0;
	inline static void(*FuncUpGetGuardState)(int goalState) = 0;
	inline static void(*FuncUpGetUpgradeId)(int player, int count, int goalTypeId, int goalUpgradeId) = 0;
	inline static void(*FuncUpOutOfSync)() = 0;
#endif
};
