#pragma once
#include <vector>

#include <stdint.h>

class ExpertFact
{
public:
	static void UpdateAddresses();
	static void EvaluateRelOpCalled(int value);

	static int AttackSoldierCount();
	static int AttackWarboatCount();
	static bool BuildingAvailable(int buildingType);
	static int BuildingCount();
	static int BuildingCountTotal();
	static int BuildingTypeCount(int buildingType);
	static int BuildingTypeCountTotal(int buildingType);
	static bool CanAffordBuilding(int buildingType);
	static bool CanAffordCompleteWall(int perimeter, int wallType);
	static bool CanAffordResearch(int researchType);
	static bool CanAffordUnit(int unitType);
	static bool CanBuild(int buildingType);
	static bool CanBuildGate(int perimeter);
	static bool CanBuildGateWithEscrow(int perimeter);
	static bool CanBuildWall(int perimeter, int wallType, int escrowFlag);
	static bool CanBuildWallWithEscrow(int perimeter, int wallType);
	static bool CanBuildWithEscrow(int buildingType);
	static bool CanBuyCommodity(int commodityType);
	static bool CanResearch(int researchType);
	static bool CanResearchWithEscrow(int researchType);
	static bool CanSellCommodity(int commodityType);
	static bool CanSpy();
	static bool CanSpyWithEscrow();
	static bool CanTrain(int unitType);
	static bool CanTrainWithEscrow(int unitType);
	static int CcPlayersBuildingCount(int playerNumber);
	static int CcPlayersBuildingTypeCount(int playerNumber, int buildingType);
	static int CcPlayersUnitCount(int playerNumber);
	static int CcPlayersUnitTypeCount(int playerNumber, int unitType);
	static bool CheatsEnabled();
	static bool CivSelected(int civ);
	static int CivilianPopulation();
	static int CommodityBuyingPrice(int commodityType);
	static int CommoditySellingPrice(int commodityType);
	static int CurrentAge();
	static int CurrentAgeTime();
	static int CurrentScore();
	static bool DeathMatchGame();
	static int DefendSoldierCount();
	static int DefendWarboatCount();
	static int Difficulty();
	static bool Doctrine(int value);
	static int DropsiteMinDistance(int resourceType);
	static int EndingAge();
	static bool EnemyBuildingsInTown();
	static bool EnemyCapturedRelics();
	static int EscrowAmount(int resourceType);
	static bool EventDetected(int eventType, int id);
	static bool False();
	static bool FeCanBuildAtPoint(int param1, int param2, int param3, int param4);
	static int FoodAmount();
	static int GameTime();
	static int GameType();
	static int GateCount(int perimeter);
	static int Goal(int goalId);
	static std::vector<unsigned int> Goals();
	static int GoldAmount();
	static bool HoldKohRuin();
	static bool HoldRelics();
	static int HousingHeadroom();
	static int IdleFarmCount();
	static bool MapSize(int mapSize);
	static bool MapType(int mapType);
	static int MilitaryPopulation();
	static bool PlayerComputer(int playerNumber);
	static bool PlayerHuman(int playerNumber);
	static bool PlayerInGame(int playerNumber);
	static bool PlayerNumber(int playerNumber);
	static bool PlayerResigned(int playerNumber);
	static bool PlayerValid(int playerNumber);
	static bool PlayersAchievements(int param1, int param2, int param3, int param4);
	static int PlayersBuildingCount(int playerNumber);
	static int PlayersBuildingTypeCount(int playerNumber, int buildingType);
	static bool PlayersCiv(int playerNumber);
	static int PlayersCivilianPopulation(int playerNumber);
	static int PlayersCurrentAge(int playerNumber);
	static int PlayersCurrentAgeTime(int playerNumber);
	static int PlayersMilitaryPopulation(int playerNumber);
	static int PlayersPopulation(int playerNumber);
	static int PlayersScore(int playerNumber);
	static bool PlayersStance(int playerNumber, int stance);
	static int PlayersTribute(int playerNumber, int resourceType);
	static int PlayersTributeMemory(int playerNumber, int resourceType);
	static int PlayersUnitCount(int playerNumber);
	static int PlayersUnitTypeCount(int playerNumber, int unitType);
	static int Population();
	static int PopulationCap();
	static int PopulationHeadroom();
	static int RandomNumber();
	static bool RegicideGame();
	static bool ResearchAvailable(int researchType);
	static bool ResearchCompleted(int researchType);
	static bool ResourceFound(int resourceType);
	static bool SharedGoal(int goalId, int value);
	static bool SheepAndForageTooFar();
	static int SoldierCount();
	static bool StanceToward(int playerNumber, int stance);
	static int StartingAge();
	static int StartingResources();
	static int StoneAmount();
	static int StrategicNumber(int strategicNumber);
	static bool TauntDetected(int playerNumber, int tauntId);
	static bool TimerTriggered(int timerId);
	static bool TownUnderAttack();
	static bool TraceFact(int param);
	static bool True();
	static bool UnitAvailable(int unitType);
	static int UnitCount();
	static int UnitCountTotal();
	static int UnitTypeCount(int unitType);
	static int UnitTypeCountTotal(int unitType);
	static int UpAlliedGoal(int computerAlly, int goalId);
	static int UpAlliedResourceAmount(int ally, int resourceAmount);
	static int UpAlliedResourcePercent(int ally, int resourceAmount);
	static int UpAlliedSn(int computerAlly, int snId);
	static int UpAttackerClass();
	static int UpBuildingTypeInTown(int typeOp, int buildingId);
	static bool UpCanBuild(int escrowState, int typeOp, int buildingId);
	static bool UpCanBuildLine(int escrowState, int goalPoint, int typeOp, int buildingId);
	static bool UpCanResearch(int escrowState, int typeOp, int techId);
	static bool UpCanSearch(int searchSource);
	static bool UpCanTrain(int escrowState, int typeOp, int unitId);
	static int UpDefenderCount();
	static int UpEnemyBuildingsInTown();
	static int UpEnemyUnitsInTown();
	static int UpEnemyVillagersInTown();
	static int UpGaiaTypeCount(int typeOp, int resource);
	static int UpGaiaTypeCountTotal(int typeOp, int resource);
	static int UpGroupSize(int typeOp, int groupId);
	static int UpIdleUnitCount(int idleType);
	static int UpObjectData(int objectData);
	static int UpObjectTargetData(int objectData);
	static int UpObjectTypeCount(int typeOp, int objectId);
	static int UpObjectTypeCountTotal(int typeOp, int objectId);
	static int UpPathDistance(int goalPoint, int strict);
	static int UpPendingObjects(int typeOp, int objectId);
	static bool UpPendingPlacement(int typeOp, int buildingId);
	static int UpPlayerDistance(int player);
	static int UpPlayersInGame(int playerStance);
	static bool UpPointContains(int goalPoint, int typeOp, int objectId);
	static int UpPointDistance(int goalPoint1, int goalPoint2);
	static int UpPointElevation(int goalPoint);
	static bool UpPointExplored(int goalPoint);
	static int UpPointTerrain(int goalPoint);
	static int UpPointZone(int goalPoint);
	static int UpProjectileDetected(int projectileType);
	static int UpProjectileTarget(int projectileType);
	static int UpRemainingBoarAmount();
	static int UpResearchStatus(int typeOp, int techId);
	static int UpResourceAmount(int resourceAmount);
	static int UpResourcePercent(int resourceAmount);
	static int UpTimerStatus(int timerId);
	static bool UpTrainSiteReady(int typeOp, int unitId);
	static int UpUnitTypeInTown(int typeOp, int unitId);
	static int UpVillagerTypeInTown(int typeOp, int unitId);
	static bool VictoryCondition(int victoryCondition);
	static int WallCompletedPercentage(int perimeter);
	static int WallInvisiblePercentage(int perimeter);
	static int WarboatCount();
	static int WoodAmount();

private:
	ExpertFact() {};

	inline static int lastRelOpValue = 0;
	inline static void** informationAi;

	// params might need reviewing
	inline static intptr_t(__fastcall* FuncAttackSoldierCount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncAttackWarboatCount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncBuildingAvailable)(int buildingType) = 0;
	inline static intptr_t(__fastcall* FuncBuildingCount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncBuildingCountTotal)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncBuildingTypeCount)(int buildingType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncBuildingTypeCountTotal)(int buildingType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncCanAffordBuilding)(int buildingType) = 0;
	inline static intptr_t(__fastcall* FuncCanAffordCompleteWall)(int perimeter, int wallType) = 0;
	inline static intptr_t(__fastcall* FuncCanAffordResearch)(int researchType) = 0;
	inline static intptr_t(__fastcall* FuncCanAffordUnit)(int unitType) = 0;
	inline static intptr_t(__fastcall* FuncCanBuild)(int buildingType) = 0;
	inline static intptr_t(__fastcall* FuncCanBuildGate)(int perimeter) = 0;
	inline static intptr_t(__fastcall* FuncCanBuildGateWithEscrow)(int perimeter) = 0;
	inline static intptr_t(__fastcall* FuncCanBuildWall)(int perimeter, int wallType, int escrowFlag) = 0;
	inline static intptr_t(__fastcall* FuncCanBuildWallWithEscrow)(int perimeter, int wallType) = 0;
	inline static intptr_t(__fastcall* FuncCanBuildWithEscrow)(int buildingType) = 0;
	inline static intptr_t(__fastcall* FuncCanBuyCommodity)(int commodityType) = 0;
	inline static intptr_t(__fastcall* FuncCanResearch)(int researchType) = 0;
	inline static intptr_t(__fastcall* FuncCanResearchWithEscrow)(int researchType) = 0;
	inline static intptr_t(__fastcall* FuncCanSellCommodity)(int commodityType) = 0;
	inline static intptr_t(__fastcall* FuncCanSpy)() = 0;
	inline static intptr_t(__fastcall* FuncCanSpyWithEscrow)() = 0;
	inline static intptr_t(__fastcall* FuncCanTrain)(int unitType) = 0;
	inline static intptr_t(__fastcall* FuncCanTrainWithEscrow)(int unitType) = 0;
	inline static intptr_t(__fastcall* FuncCcPlayersBuildingCount)(int playerNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncCcPlayersBuildingTypeCount)(int playerNumber, int buildingType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncCcPlayersUnitCount)(int playerNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncCcPlayersUnitTypeCount)(int playerNumber, int unitType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncCheatsEnabled)() = 0;
	inline static intptr_t(__fastcall* FuncCivSelected)(int civ) = 0;
	inline static intptr_t(__fastcall* FuncCivilianPopulation)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncCommodityBuyingPrice)(int commodityType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncCommoditySellingPrice)(int commodityType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncCurrentAge)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncCurrentAgeTime)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncCurrentScore)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncDeathMatchGame)() = 0;
	inline static intptr_t(__fastcall* FuncDefendSoldierCount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncDefendWarboatCount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncDifficulty)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncDoctrine)(int value) = 0;
	inline static intptr_t(__fastcall* FuncDropsiteMinDistance)(int resourceType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncEndingAge)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncEnemyBuildingsInTown)() = 0;
	inline static intptr_t(__fastcall* FuncEnemyCapturedRelics)() = 0;
	inline static intptr_t(__fastcall* FuncEscrowAmount)(int resourceType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncEventDetected)(int eventType, int id) = 0;
	inline static intptr_t(__fastcall* FuncFalse)() = 0;
	inline static intptr_t(__fastcall* FuncFeCanBuildAtPoint)(int param1, int param2, int param3, int param4) = 0;
	inline static intptr_t(__fastcall* FuncFoodAmount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncGameTime)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncGameType)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncGateCount)(int perimeter, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncGoal)(int goalId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncGoals)() = 0;
	inline static intptr_t(__fastcall* FuncGoldAmount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncHoldKohRuin)() = 0;
	inline static intptr_t(__fastcall* FuncHoldRelics)() = 0;
	inline static intptr_t(__fastcall* FuncHousingHeadroom)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncIdleFarmCount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncMapSize)(int mapSize) = 0;
	inline static intptr_t(__fastcall* FuncMapType)(int mapType) = 0;
	inline static intptr_t(__fastcall* FuncMilitaryPopulation)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayerComputer)(int playerNumber) = 0;
	inline static intptr_t(__fastcall* FuncPlayerHuman)(int playerNumber) = 0;
	inline static intptr_t(__fastcall* FuncPlayerInGame)(int playerNumber) = 0;
	inline static intptr_t(__fastcall* FuncPlayerNumber)(int playerNumber) = 0;
	inline static intptr_t(__fastcall* FuncPlayerResigned)(int playerNumber) = 0;
	inline static intptr_t(__fastcall* FuncPlayerValid)(int playerNumber) = 0;
	inline static intptr_t(__fastcall* FuncPlayersAchievements)(int param1, int param2, int param3, int param4) = 0;
	inline static intptr_t(__fastcall* FuncPlayersBuildingCount)(int playerNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersBuildingTypeCount)(int playerNumber, int buildingType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersCiv)(int playerNumber) = 0;
	inline static intptr_t(__fastcall* FuncPlayersCivilianPopulation)(int playerNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersCurrentAge)(int playerNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersCurrentAgeTime)(int playerNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersMilitaryPopulation)(int playerNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersPopulation)(int playerNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersScore)(int playerNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersStance)(int playerNumber, int stance) = 0;
	inline static intptr_t(__fastcall* FuncPlayersTribute)(int playerNumber, int resourceType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersTributeMemory)(int playerNumber, int resourceType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersUnitCount)(int playerNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPlayersUnitTypeCount)(int playerNumber, int unitType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPopulation)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPopulationCap)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncPopulationHeadroom)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncRandomNumber)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncRegicideGame)() = 0;
	inline static intptr_t(__fastcall* FuncResearchAvailable)(int researchType) = 0;
	inline static intptr_t(__fastcall* FuncResearchCompleted)(int researchType) = 0;
	inline static intptr_t(__fastcall* FuncResourceFound)(int resourceType) = 0;
	inline static intptr_t(__fastcall* FuncSharedGoal)(int goalId, int value) = 0;
	inline static intptr_t(__fastcall* FuncSheepAndForageTooFar)() = 0;
	inline static intptr_t(__fastcall* FuncSoldierCount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncStanceToward)(int playerNumber, int stance) = 0;
	inline static intptr_t(__fastcall* FuncStartingAge)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncStartingResources)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncStoneAmount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncStrategicNumber)(int strategicNumber, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncTauntDetected)(int playerNumber, int tauntId) = 0;
	inline static intptr_t(__fastcall* FuncTimerTriggered)(int timerId) = 0;
	inline static intptr_t(__fastcall* FuncTownUnderAttack)() = 0;
	inline static intptr_t(__fastcall* FuncTraceFact)(int param) = 0;
	inline static intptr_t(__fastcall* FuncTrue)() = 0;
	inline static intptr_t(__fastcall* FuncUnitAvailable)(int unitType) = 0;
	inline static intptr_t(__fastcall* FuncUnitCount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUnitCountTotal)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUnitTypeCount)(int unitType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUnitTypeCountTotal)(int unitType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpAlliedGoal)(int computerAlly, int goalId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpAlliedResourceAmount)(int ally, int resourceAmount, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpAlliedResourcePercent)(int ally, int resourceAmount, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpAlliedSn)(int computerAlly, int snId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpAttackerClass)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpBuildingTypeInTown)(int typeOp, int buildingId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpCanBuild)(int escrowState, int typeOp, int buildingId) = 0;
	inline static intptr_t(__fastcall* FuncUpCanBuildLine)(int escrowState, int goalPoint, int typeOp, int buildingId) = 0;
	inline static intptr_t(__fastcall* FuncUpCanResearch)(int escrowState, int typeOp, int techId) = 0;
	inline static intptr_t(__fastcall* FuncUpCanSearch)(int searchSource) = 0;
	inline static intptr_t(__fastcall* FuncUpCanTrain)(int escrowState, int typeOp, int unitId) = 0;
	inline static intptr_t(__fastcall* FuncUpDefenderCount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpEnemyBuildingsInTown)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpEnemyUnitsInTown)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpEnemyVillagersInTown)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpGaiaTypeCount)(int typeOp, int resource, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpGaiaTypeCountTotal)(int typeOp, int resource, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpGroupSize)(int typeOp, int groupId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpIdleUnitCount)(int idleType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpObjectData)(int objectData, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpObjectTargetData)(int objectData, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpObjectTypeCount)(int typeOp, int objectId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpObjectTypeCountTotal)(int typeOp, int objectId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpPathDistance)(int goalPoint, int strict, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpPendingObjects)(int typeOp, int objectId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpPendingPlacement)(int typeOp, int buildingId) = 0;
	inline static intptr_t(__fastcall* FuncUpPlayerDistance)(int player, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpPlayersInGame)(int playerStance, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpPointContains)(int goalPoint, int typeOp, int objectId) = 0;
	inline static intptr_t(__fastcall* FuncUpPointDistance)(int goalPoint1, int goalPoint2, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpPointElevation)(int goalPoint, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpPointExplored)(int goalPoint) = 0;
	inline static intptr_t(__fastcall* FuncUpPointTerrain)(int goalPoint, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpPointZone)(int goalPoint, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpProjectileDetected)(int projectileType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpProjectileTarget)(int projectileType, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpRemainingBoarAmount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpResearchStatus)(int typeOp, int techId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpResourceAmount)(int resourceAmount, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpResourcePercent)(int resourceAmount, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpTimerStatus)(int timerId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpTrainSiteReady)(int typeOp, int unitId) = 0;
	inline static intptr_t(__fastcall* FuncUpUnitTypeInTown)(int typeOp, int unitId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncUpVillagerTypeInTown)(int typeOp, int unitId, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncVictoryCondition)(int victoryCondition) = 0;
	inline static intptr_t(__fastcall* FuncWallCompletedPercentage)(int perimeter, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncWallInvisiblePercentage)(int perimeter, int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncWarboatCount)(int relOp, int value) = 0;
	inline static intptr_t(__fastcall* FuncWoodAmount)(int relOp, int value) = 0;
};
