#pragma once
#include "google/protobuf/any.pb.h"

#include "misc/Configuration.h"
#include "expert/fact/ExpertFact.h"
#include "protos/expert/fact/fact.pb.h"

class ExpertFactHandler
{
public:
	// facts
	static void AttackSoldierCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void AttackWarboatCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void BuildingAvailable(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void BuildingCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void BuildingCountTotal(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void BuildingTypeCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void BuildingTypeCountTotal(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanAffordBuilding(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanAffordCompleteWall(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanAffordResearch(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanAffordUnit(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanBuild(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanBuildGate(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanBuildGateWithEscrow(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanBuildWall(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanBuildWallWithEscrow(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanBuildWithEscrow(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanBuyCommodity(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanResearch(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanResearchWithEscrow(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanSellCommodity(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanSpy(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanSpyWithEscrow(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanTrain(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CanTrainWithEscrow(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CcPlayersBuildingCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CcPlayersBuildingTypeCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CcPlayersUnitCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CcPlayersUnitTypeCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CheatsEnabled(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CivSelected(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CivilianPopulation(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CommodityBuyingPrice(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CommoditySellingPrice(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CurrentAge(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CurrentAgeTime(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void CurrentScore(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void DeathMatchGame(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void DefendSoldierCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void DefendWarboatCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void Difficulty(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void Doctrine(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void DropsiteMinDistance(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void EnemyBuildingsInTown(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void EnemyCapturedRelics(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void EscrowAmount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void EventDetected(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void False(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void FoodAmount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void GameTime(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void GameType(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void GateCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void Goal(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void GoalList(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void GoldAmount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void HoldKohRuin(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void HoldRelics(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void HousingHeadroom(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void IdleFarmCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void MapSize(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void MapType(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void MilitaryPopulation(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayerComputer(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayerHuman(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayerInGame(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayerNumber(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayerResigned(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayerValid(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersAchievements(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersBuildingCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersBuildingTypeCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersCiv(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersCivilianPopulation(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersCurrentAge(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersCurrentAgeTime(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersMilitaryPopulation(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersPopulation(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersScore(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersStance(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersTribute(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersTributeMemory(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersUnitCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PlayersUnitTypeCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void Population(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PopulationCap(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void PopulationHeadroom(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void RandomNumber(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void RegicideGame(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void ResearchAvailable(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void ResearchCompleted(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void ResourceFound(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void SharedGoal(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void SheepAndForageTooFar(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void SoldierCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void StanceToward(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void StartingAge(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void StartingResources(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void StoneAmount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void StrategicNumber(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void StrategicNumberList(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void TauntDetected(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void TimerTriggered(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void TownUnderAttack(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void TraceFact(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void True(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UnitAvailable(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UnitCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UnitCountTotal(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UnitTypeCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UnitTypeCountTotal(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpAlliedGoal(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpAlliedResourceAmount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpAlliedResourcePercent(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpAlliedSn(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpAttackerClass(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpBuildingTypeInTown(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpCanBuild(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpCanBuildLine(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpCanResearch(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpCanSearch(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpCanTrain(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpDefenderCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpEnemyBuildingsInTown(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpEnemyUnitsInTown(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpEnemyVillagersInTown(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpGaiaTypeCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpGaiaTypeCountTotal(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpGroupSize(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpIdleUnitCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpObjectData(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpObjectDataList(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpObjectTargetData(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpObjectTypeCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpObjectTypeCountTotal(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPathDistance(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPendingObjects(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPendingPlacement(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPlayerDistance(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPlayersInGame(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPointContains(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPointDistance(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPointElevation(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPointExplored(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPointTerrain(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpPointZone(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpProjectileDetected(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpProjectileTarget(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpRemainingBoarAmount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpResearchStatus(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpResourceAmount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpResourcePercent(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpSearchObjectIdList(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpTimerStatus(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpTrainSiteReady(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpUnitTypeInTown(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void UpVillagerTypeInTown(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void VictoryCondition(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void WallCompletedPercentage(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void WallInvisiblePercentage(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void WarboatCount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void WoodAmount(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	// DE-only facts
	static void EndingAge(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void FeCanBuildAtPoint(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void FeSubGameType(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);

	static void ModMapDimensions(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);
	static void ModMapTiles(const google::protobuf::Any& anyCommand, google::protobuf::Any* anyResult);

private:
	ExpertFactHandler() {};

	static int GeneralizeTerrainType(int terrainId);
};
